### PR TITLE
refactor launch listener to automatically trigger on any run configur…

### PR DESCRIPTION
**Pull request by dwightguth**
…ation

@traiansf please review

This is somewhat simpler. We are using launchRemoved to clean up and a map so that a separate thread gets created for each launch. I would prefer not to be based on launches at all but it seems that that's a requirement for the Valgrind part of the code.

With this code, plus the pull request I will create in the rv match repo, once pushed to the update site, it should work so that any run configuration configured with kcc will automatically make the plugin work.

Things we still need to do:
- put translation errors in the rv-match pane
- don't clear the error panes unless explicitly asked by the user.

### CODE REVIEW

**Comment by traiansf** [comment]
It does not seem to work properly.  I currently get a deadlock because ReporterThread.terminate() calls join, while I suspect the thread is blocked waiting for something to be sent on the pipe on which nothing was sent.

**Comment by dwightguth** [comment]
did you build runtimeverification/rv-match#281 first though?

**Comment by traiansf** [comment]
looks good to me.
It works now with the rv-match build you mentioned, and the design seems much simpler.

One reason for which valgrind requires the launch is because it uses it to resolve file locations.

**Comment by dwightguth** [comment]
You will have to merge this because I don't have commit rights to this repo yet.

**Comment by traiansf** [comment]
I've merged it and given the rv-match team write access to the repo.  Sorry for the delay.

**Pull request merged**
